### ISSUE TITLE
one question：How to build pyconv-darknet53？thanks！

### ISSUE THREAD

**Issue by lizhimll** [iduta/pyconv#11]

**Comment by iduta** [comment]
You can start by converting the standard 3x3 convolution to PyConv as in our code. I also added two examples of basic building blocks using PyConv in https://github.com/iduta/pyconv/blob/master/models/pyconvresnet.py

**Comment by lizhimll** [comment]
> You can start by converting the standard 3x3 convolution to PyConv as in our code. I also added two examples of basic building blocks using PyConv in https://github.com/iduta/pyconv/blob/master/models/pyconvresnet.py
thank you!
