### ISSUE TITLE
Can you give the model for object detection?

### ISSUE THREAD

**Issue by Smallwhite999** [iduta/pyconv#12]
Hello, do you have a model for object detection? For example, fast RCNN's res or Vgg network

**Comment by iduta** [comment]
Hello! Sorry, I don't have the model for fast RCNN or VGG network.

**Comment by Smallwhite999** [comment]
> 
> 
> Hello! Sorry, I don't have the model for fast RCNN or VGG network.

OK，Thanks，Can this Pyconv be used in the fast RCNN backbone network RESNET?

**Comment by iduta** [comment]
> > Hello! Sorry, I don't have the model for fast RCNN or VGG network.
> 
> OK，Thanks，Can this Pyconv be used in the fast RCNN backbone network RESNET?

Yes, definitely.
