### ISSUE TITLE
Can you give the model for semantic segmentaion?

### ISSUE THREAD

**Issue by chuxiang93** [iduta/pyconv#2]
Good Job! I wonder to know more about details of model for semantic segmentation, can you give it?
Thank you.

**Comment by iduta** [comment]
Thank you! I will make the model available in the close future.

**Comment by iduta** [comment]
Please see this repository https://github.com/iduta/pyconvsegnet for our model for semantic segmentation.

**Comment by chuxiang93** [comment]
Great! Thank you.
