### ISSUE TITLE
Comparison with mixconv?

### ISSUE THREAD

**Issue by chris-ha458** [iduta/pyconv#3]
MixConv from google (https://arxiv.org/abs/1907.09595) is another model that explores different types of filters with varying size and depth.

MixNet-M (params 4.1M 256Mflops Top-1 23% ) roughly corresponds to ResNet-50(Top-1 23.88%params25.56 4.14Gflops) and pyconv50(Top-1 22.12% param 24.85, 3.88Gflops)

While MixNet-L(21.1%) roughly corresponds to ResNet-152 and Pyconv101

The parameter counts and flops numbers arent really comparable since MixNet is an MNAS- based architecture which shows extremely low throughput and latency on GPUs.
Also, because of that, it is very different from ResNet in structure.

![image](https://user-images.githubusercontent.com/15088501/85937664-b5f50280-b940-11ea-8426-dbddbc486fe2.png)

I could not find actual training time (time.time or wall time) and only epochs, it is hard to see if your network is harder or easier to train compared to ResNets.

Also, Res2Net(https://arxiv.org/abs/1904.01169) and BigLittleNet are other networks that seem to be worthy of comparison considering the ResNet based nature of your work.

![res2net](https://user-images.githubusercontent.com/15088501/85937732-577c5400-b941-11ea-8b06-09e53dd80914.jpg)

In the case of Res2Net, it also preserves the macro structure of ResNet. Res2Net which would be comparable to pyconvResNet50 shows a marginal improvement(Top-1 22.01 Top-5 6.15) which I consider within margin of error.

Thank you for your work.

**Comment by iduta** [comment]
Thank you for pointing out these works!

Regarding the comparison with MixConv, I will only highlight 2 differences:

1. Our work presents an approach to convert a standard convolution in a pyramidal counterpart (PyConv, with different kernel sizes and depths) while preserving the number of parameters and computational costs.
 
2. MixConv splits the input feature maps into groups and applies independently a different kernel size for each group, as we can see from the paper that you pointed out:
<img width="514" alt="Screen Shot 2020-06-28 at 11 11 14 AM" src="https://user-images.githubusercontent.com/15975961/85940890-50007f00-b930-11ea-9945-cfb196d652ec.png">
Thus each kernel size has only access to a limited portion of the input feature maps. For instance, if there are four kernel sizes: 3x3, 5x5, 7x7, 9x9, and 64 input feature maps, then MixConv will run the 3x3 kernel convolution only on the first 16 input feature maps (without having access to the remaining 48 input feature maps). The 5x5 will only run on the next 16 input feature maps (similarly, without having access the the other input feature maps) and so on. 
Our PyConv is fundamentally different than MixConv as in our approach each level of PyConv has access to all input feature maps. Considering the same example, with four kernels, the first level of our PyConv,  with 3x3 kernel size,  receives all 64 input channels and splits them in a number of groups and performs the 3x3 convolution with a specific depth. Thus the 3x3 kernel size has access to all input feature maps. The next level on PyConv, 5x5 kernel, also receives all input feature maps, but splits the features maps in a higher number of groups (thus different kernel depth) and so on for all the levels.

The main goal of our PyConv is to perform multi-scale processing of the input (by using different kernel sizes over the whole input) for capturing different level of details.  While MixConv applies a kernel size only on one part of the input, I don't actually see the motivation of why, for instance, the first 16 input feature maps should get a 3x3 kernel size and the last 16 input feature maps should get a 9x9 kernel size. Basically, if we take any input feature map, in the MixConv approach only a single kernel size is assigned to it while in our PyConv any particular input feature map receives multiple kernel sizes and connectivities (depending on the chosen PyConv levels).

Regarding the time, note that MixNet is designed using NAS and for mobile cases, thus the authors optimized the network also for efficiency. We present here a "naive" implementation  in PyTorch, we have not optimized for throughput yet. The throughput can be significantly improved if more optimized implementations/configurations of PyConv are explored. Theoretically PyConv has the potential of being very fast as all levels can be computed in parallel. So, for instance, an optimized implementation of PyConv integrated directly in the deep learning libraries (for instance in NVIDIA cuDNN) can give significant boost in speed. We hope in the future PyConv will be directly integrated in the deep learning libraries, for instance, PyConv may have a similar path as grouped convolution, which was later integrated in cuDNN. I don't see a major reason to limiting the efficiency improvements on PyConv.

Regarding the recognition performance comparisons that you pointed out, we need first to make sure that the training settings are the same for a fair comparison. You reported our results which are obtained with the basic training settings. As we presented in our paper, just slightly changing the training settings can influence significantly the results (for instance, the PyConvResNet can easily improve the top-1 error from 22.12 to 20.56, as we show in our paper). 


Regarding BigLittleNet,  PyConv is a quite different concept. BigLittleNet work proposes a module with 2 branches where one branch performs downsampling and then upsampling of the input, while our approach proposes a direct replacement of the standard convolution to implicitly integrate multi-scale processing.

Regarding the comparison  with Res2Net, not only the approach is different and it has a quite similar concept as we highlighted for MixConv at point 2., it has also a serious efficiency limitation. As we can directly see from the figure that you uploaded here, the Res2Net kernels K2, K3 and K4 run sequentially, so to compute y3 it is necessary to first compute y2 and to compute y4 requires first to compute y2 and y3. This looks a major drawback in improving the throughput of Res2Net, while all levels of our PyConv can run in parallel, therefore, PyConv has a lot of room for improvement.


Hope these explanations can help!
